{
    'name': 'Marketplace - Service Après Vente (SAV)',
    'version': '16.0.1.0.0',
    'category': 'Sales/Service',
    'summary': 'Service Après Vente (SAV) / After-Sales Service Management',
    'description': 'Complete SAV ticket management system with tree, form, kanban, search, calendar, graph, and pivot views',
    'author': 'ElysiumShop Dev Team',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'sale',
        'product',
    ],
    'data': [
        'security/sav_security.xml',
        'security/ir.model.access.csv',
        'views/sav_ticket_views.xml',
        'views/sav_ticket_search.xml',
        'views/sav_ticket_calendar.xml',
        'views/sav_ticket_graph.xml',
        'views/sav_ticket_pivot.xml',
        'views/actions.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
